version: '3.9'
services:
# ===========================
# クライアントサーバー
# ===========================
  CLIENT:
    image: node:21
    tty: true
    volumes:
      - ../Client:/client
    ports:
      - 4500:5173